name: Java CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: 17

      - name: Build using maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Render deploy
        run: curl "${{secrets.RENDER_DEPLOY_HOOK}}"